### ISSUE TITLE
Kernel Start Issue 

### ISSUE THREAD

**Issue by NicolaBernini** [xtreamsrl/polynote-docker#1] opened 2019-11-03 10:22 UTC
# Overview 

The Kernel does not seem to start so I have run the container without the -d option to see the log and this is the error message I see 

```
[INFO]  Deploying with command:
        spark-submit --class polynote.kernel.remote.RemoteKernelClient --driver-java-options "-Dlog4j.configuration
=log4j.properties -Djava.library.path=/jep" --driver-memory 20g --cluster trionplay_useast1prod --ver 2.1.1-dra --j
ars file:/usr/src/app/polynote/deps/polynote-spark-runtime.jar,file:/usr/src/app/polynote/deps/polynote-runtime.jar
 --conf spark.driver.userClassPathFirst=false --conf spark.executor.userClassPathFirst=false --conf polynote.kernel
.remote=true /usr/src/app/polynote/polynote.jar --address 172.17.0.2 --port 32799 --kernelFactory polynote.kernel.L
ocalSparkKernelFactory
/opt/conda/bin/spark-submit: line 27: /spark/bin/spark-class: No such file or directory

[ERROR] Kernel error
      : java.util.concurrent.TimeoutException: Remote kernel process failed to start after 180000000000 nanoseconds
        polynote.kernel.remote.SocketTransport$$anonfun$polynote$kernel$remote$SocketTransport$$startConnection$3.a
pply(transport.scala:203)
```

**Comment by rmaganza** [comment] 2019-11-05 14:38
Thank you for pointing this out.

This was caused by a mis-set environment variable and has been fixed by 8b47d1ddfe9d5707913a7599d8578a1495745a24. :)

**Closed as completed** 2019-11-05 15:22 UTC
Labels: bug, good first issue
